CREATE TABLE IF NOT EXISTS activities (
  id INTEGER PRIMERY KEY AUTOINCREMENT,
  name TEXT NOT NULL,
  description TEXT,
  amount REAL NOT NULL,
  activities_date DATE,
  due_date DATE,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
